#!/bin/sh

function checkEmail() {

  EMAIL=${1}
  EMAIL_LEN=${#EMAIL}

  EXPECTED_EMAIL_DOMAIN="@users.noreply.github.com"
  EXPECTED_EMAIL_DOMAIN_LEN=${#EXPECTED_EMAIL_DOMAIN}

  if [[ ${EMAIL} != *"${EXPECTED_EMAIL_DOMAIN}" ]]
  then
    echo 'email expected domain of '\'${EXPECTED_EMAIL_DOMAIN}\';
    echo '';
    exit 1;
  fi

  if [[ "${EMAIL_LEN}" -le "${EXPECTED_EMAIL_DOMAIN_LEN}" ]]
  then
    echo 'email missing username for '\'${EXPECTED_EMAIL_DOMAIN}\';
    echo '';
    exit 1;
  fi
}

# Check tests all live within a .tests. sub package to prep for Java 11
function checkJava11TestsPrep() {
  CNT=`find . -type f | grep src/test/java | grep -v tests | wc -l`
  if [[ "${CNT}" -ne 0 ]]; then
    echo 'Java 11 Tests Prep, move tests into a '\'tests\'' subpackage';
    find . -type f | grep src/test/java | grep -v tests
    echo '';
    exit 1;
  fi
}

checkEmail "$(git config user.email)"
checkJava11TestsPrep
