#!/bin/sh

function checkEmail() {

  EMAIL=$(git config user.email)
  EMAIL_LEN=${#EMAIL}

  EXPECTED_EMAIL_DOMAIN="@users.noreply.github.com"
  EXPECTED_EMAIL_DOMAIN_LEN=${#EXPECTED_EMAIL_DOMAIN}

  if [[ ${EMAIL} != *"${EXPECTED_EMAIL_DOMAIN}" ]]
  then
    echo 'email expected domain of '${EXPECTED_EMAIL_DOMAIN};
    echo '';
    exit 1;
  fi

  if [[ "${EMAIL_LEN}" -le "${EXPECTED_EMAIL_DOMAIN_LEN}" ]]
  then
    echo 'email missing username for '${EXPECTED_EMAIL_DOMAIN};
    echo '';
    exit 1;
  fi
}

checkEmail
