#!/bin/sh

function checkEmail() {

  EMAIL=${1}
  EMAIL_LEN=${#EMAIL}

  EXPECTED_EMAIL_DOMAIN="@users.noreply.github.com"
  EXPECTED_EMAIL_DOMAIN_LEN=${#EXPECTED_EMAIL_DOMAIN}

  if [[ ${EMAIL} != *"${EXPECTED_EMAIL_DOMAIN}" ]]
  then
    echo 'email expected domain of '\'${EXPECTED_EMAIL_DOMAIN}\';
    echo '';
    exit 1;
  fi

  if [[ "${EMAIL_LEN}" -le "${EXPECTED_EMAIL_DOMAIN_LEN}" ]]
  then
    echo 'email missing username for '\'${EXPECTED_EMAIL_DOMAIN}\';
    echo '';
    exit 1;
  fi
}

function checkName() {

  NAME=${1}

  # checks name for any leading, trailing or multiple whitespace matches
  NAME_WHITESPACE='((^ )|( $)|(  +)|( +(.*) +))'

  if [[ ${NAME} =~ $NAME_WHITESPACE ]]
  then
    echo 'name invalid whitespace, leading, trailing or multiple '\'${NAME}\';
    echo '';
    exit 1;
  fi

  # checks name if space then only an initial surname match
  SURNAME_INITIAL='\.*([:space:][^:space:][^:space:])$'

  if [[ ${NAME} =~ $SURNAME_INITIAL ]]
  then
    echo $BASH_REMATCH[0]
    echo $BASH_REMATCH[1]
    echo $BASH_REMATCH[2]
    echo $BASH_REMATCH[3]
    echo $BASH_REMATCH[4]
    echo 'surname can only be an initial character '\'${NAME}\';
    echo '';
    exit 1;
  fi
}

# Check tests all live within a .tests. sub package to prep for Java 11
function checkJava11TestsPrep() {
  CNT=`find . -type f | grep src/test/java | grep -v tests | wc -l`
  if [[ "${CNT}" -ne 0 ]]; then
    echo 'Java 11 Tests Prep, move tests into a '\'tests\'' subpackage';
    find . -type f | grep src/test/java | grep -v tests
    echo '';
    exit 1;
  fi
}

checkEmail "$(git config user.email)"
checkName "$(git config user.name)"
checkJava11TestsPrep
